---
server:
  servlet:
    session:
      timeout: 1800  # 30 minutes
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/multi?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # TODO default db should not contain any business logic, tenant DB's are not initialized automatically => remove this
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

management:
  endpoints:
    web:
      exposure:
        include: '*'

multitenant:
  tenant-id-source: servername
  tenants:
    - name: terrible-swan-17
      datasource:
        url: jdbc:mysql://localhost:3306/multi_1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
    - name: terrible-swan-23
      datasource:
        url: jdbc:mysql://localhost:3306/multi_2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
